pagination:
  page-size: 10
spring:
  application:
    name: MoviesPlatform
  datasource:
    url: jdbc:mysql://localhost:3306/MoviesPlatform
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.fawry.moviesplatform: ERROR

  file:
    name: logs/application.log
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}] [%-5level] [%logger{36}] - %msg%n"

